/* Auto-generated by genmsg_cpp for file /home/amsl/AMSL_ros_pkg/usr_msgs/msg/Edge.msg */
#ifndef USR_MSGS_MESSAGE_EDGE_H
#define USR_MSGS_MESSAGE_EDGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "sensor_msgs/PointCloud2.h"
#include "sensor_msgs/PointCloud2.h"
#include "geometry_msgs/PoseWithCovariance.h"

namespace usr_msgs
{
template <class ContainerAllocator>
struct Edge_ {
  typedef Edge_<ContainerAllocator> Type;

  Edge_()
  : header()
  , idx_tgt(0)
  , idx_src(0)
  , cloud_tgt()
  , cloud_src()
  , r_pose()
  {
  }

  Edge_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , idx_tgt(0)
  , idx_src(0)
  , cloud_tgt(_alloc)
  , cloud_src(_alloc)
  , r_pose(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int64_t _idx_tgt_type;
  int64_t idx_tgt;

  typedef int64_t _idx_src_type;
  int64_t idx_src;

  typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_tgt_type;
   ::sensor_msgs::PointCloud2_<ContainerAllocator>  cloud_tgt;

  typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_src_type;
   ::sensor_msgs::PointCloud2_<ContainerAllocator>  cloud_src;

  typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _r_pose_type;
   ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  r_pose;


  typedef boost::shared_ptr< ::usr_msgs::Edge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usr_msgs::Edge_<ContainerAllocator>  const> ConstPtr;
}; // struct Edge
typedef  ::usr_msgs::Edge_<std::allocator<void> > Edge;

typedef boost::shared_ptr< ::usr_msgs::Edge> EdgePtr;
typedef boost::shared_ptr< ::usr_msgs::Edge const> EdgeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::usr_msgs::Edge_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::usr_msgs::Edge_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace usr_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::usr_msgs::Edge_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::usr_msgs::Edge_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::usr_msgs::Edge_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6b381e862d1efbb20a42e6a1c379609e";
  }

  static const char* value(const  ::usr_msgs::Edge_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6b381e862d1efbb2ULL;
  static const uint64_t static_value2 = 0x0a42e6a1c379609eULL;
};

template<class ContainerAllocator>
struct DataType< ::usr_msgs::Edge_<ContainerAllocator> > {
  static const char* value() 
  {
    return "usr_msgs/Edge";
  }

  static const char* value(const  ::usr_msgs::Edge_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::usr_msgs::Edge_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#file:		usr_msgs/Edge.msg\n\
#created:	2014.12.22\n\
#author:	s.shimizu\n\
\n\
Header header\n\
\n\
#idx:		index of cloud_src.\n\
#cloud_tgt:	target Pointcloud.\n\
#cloud_src:	source Pointcloud.\n\
#r_pose:	relative pose from target to source\n\
\n\
int64 idx_tgt\n\
int64 idx_src\n\
sensor_msgs/PointCloud2 cloud_tgt\n\
sensor_msgs/PointCloud2 cloud_src\n\
geometry_msgs/PoseWithCovariance r_pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::usr_msgs::Edge_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::usr_msgs::Edge_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::usr_msgs::Edge_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::usr_msgs::Edge_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.idx_tgt);
    stream.next(m.idx_src);
    stream.next(m.cloud_tgt);
    stream.next(m.cloud_src);
    stream.next(m.r_pose);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Edge_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usr_msgs::Edge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::usr_msgs::Edge_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "idx_tgt: ";
    Printer<int64_t>::stream(s, indent + "  ", v.idx_tgt);
    s << indent << "idx_src: ";
    Printer<int64_t>::stream(s, indent + "  ", v.idx_src);
    s << indent << "cloud_tgt: ";
s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud_tgt);
    s << indent << "cloud_src: ";
s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud_src);
    s << indent << "r_pose: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.r_pose);
  }
};


} // namespace message_operations
} // namespace ros

#endif // USR_MSGS_MESSAGE_EDGE_H

